# nixpacks.toml - Force JavaScript-only build
[start]
cmd = "npm start"

[build]
cmds = ["npm install --only=production"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"

[phases.install]
dependsOn = []
cmds = ["npm ci --only=production"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'JavaScript project - no build step needed'"]
